import { Flex, Grid } from "@radix-ui/themes";
import type { Metadata } from "next";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Grid
      columns={{ xs: "1fr", md: "40px 1fr" }}
      height={"100svh"}
      maxHeight={"100svh"}
      overflow={"hidden"}
      position={"relative"}
    >
      <div className="hidden lg:flex">
        <Sidebar />
      </div>
      <Flex
        direction={"column"}
        maxHeight={"100%"}
        height={"100%"}
        overflow={"hidden"}
        flexGrow={"1"}
        flexShrink={"1"}
        // className="bg-yellow-600"
      >
        <Header />
        <Flex
          // className="bg-green-800 "
          minHeight={"0"}
          overflow={"hidden"}
          flexGrow={"1"}
          flexShrink={"1"}
          p="1"
        >
          {children}
        </Flex>
        <div className="flex lg:hidden">
          <Sidebar />
        </div>
      </Flex>
    </Grid>
  );
}
